import ClientProvider from "../components/ClientProvider";
import Header from "../components/Header";
import Sidebar from "../components/Sidebar";
import "../styles/globals.css";
export const metadata = {
  title: "Amazon Web Scraper",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="flex bg-[#F7FBFF] h-screen">
        <ClientProvider>
          {" "}
          <Sidebar />
          <main
            className="p-2 pt-10 sm:p-10 max-w-[1200px] w-full mx-auto overflow-y-auto 
    
          scrollbar-thin scrollbar-thumb-gray-300 scrollbar-track-gray-100 scrollbar-thumb-rounded-full
          "
          >
            {/* Header */}
            <Header />
            {children}
          </main>
        </ClientProvider>
      </body>
    </html>
  );
}
